declare const _default: {
    version: number;
    name: string;
    center: number[];
    zoom: number;
    bearing: number;
    pitch: number;
    sources: {
        openmaptiles: {
            type: string;
            url: string;
        };
    };
    sprite: string;
    glyphs: string;
    layers: ({
        id: string;
        type: string;
        paint: {
            'background-color': string;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        source?: undefined;
        'source-layer'?: undefined;
        filter?: undefined;
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-color': string;
            'fill-opacity': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        paint: {
            'fill-color': string;
            'background-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        paint: {
            'fill-color': string;
            'fill-opacity': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        layout: {
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-dasharray': number[];
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        paint: {
            'fill-color': string;
            'fill-opacity': number;
            'fill-outline-color': string;
            'fill-antialias': {
                base: number;
                stops: (number | boolean)[][];
            };
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        paint: {
            'fill-color': string;
            'fill-opacity': number;
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        layout: {
            'line-cap': string;
            visibility?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        maxzoom: number;
        filter: string[];
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-opacity': number;
            'fill-color': string;
            'fill-translate': {
                base: number;
                stops: (number | number[])[][];
            };
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-color': string;
            'background-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        filter?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-translate': number[];
            'fill-pattern': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        filter?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        paint: {
            'fill-color': string;
            'fill-antialias': boolean;
            'background-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        filter?: undefined;
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-translate': {
                base: number;
                stops: (number | number[])[][];
            };
            'fill-outline-color': string;
            'fill-color': string;
            'fill-opacity': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        filter?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-join': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-dasharray': number[];
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-join': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': {
                stops: number[][];
                base?: undefined;
            };
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-join': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': number;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-join': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-join': string;
            visibility: string;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-dasharray': number[];
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | string[])[])[];
        paint: {
            'line-color': string;
            'line-dasharray': number[];
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-join': string;
            visibility: string;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility: string;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'line-opacity': number;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-opacity': {
                base: number;
                stops: number[][];
            };
            'fill-color': string;
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility: string;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'line-opacity': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: string[];
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'fill-color': string;
            'fill-outline-color': string;
            'fill-opacity': number;
            'fill-antialias': boolean;
            'background-color'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': number;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | string[])[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': {
                stops: number[][];
                base?: undefined;
            };
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility: string;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': number;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility: string;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': {
                stops: number[][];
                base?: undefined;
            };
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | string[])[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-opacity': number;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | string[])[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility: string;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | (string | string[])[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility: string;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | string[])[])[];
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        layout?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | string[])[])[];
        layout: {
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-dasharray': number[];
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        filter: (string | (string | number)[])[];
        layout: {
            'line-join': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-dasharray': number[];
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        filter: (string | (string | number)[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        filter: (string | (string | number)[])[];
        layout: {
            'line-cap': string;
            'line-join': string;
            visibility?: undefined;
            'text-font'?: undefined;
            'text-size'?: undefined;
            'text-field'?: undefined;
            'text-max-width'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'line-color': string;
            'line-width': {
                base: number;
                stops: number[][];
            };
            'line-opacity': {
                stops: number[][];
                base?: undefined;
            };
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'text-font': string[];
            'text-size': number;
            'text-field': string;
            'text-max-width': number;
            'text-rotation-alignment': string;
            'symbol-placement': string;
            'text-letter-spacing': number;
            'symbol-spacing': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'text-font': string[];
            'text-size': number;
            'text-field': string;
            'text-max-width': number;
            'text-rotation-alignment': string;
            'symbol-placement': string;
            'symbol-spacing': number;
            'text-letter-spacing': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'text-font': string[];
            'text-size': {
                stops: number[][];
                base?: undefined;
            };
            'text-field': string;
            'text-max-width': number;
            'text-rotation-alignment': string;
            'symbol-placement': string;
            'symbol-spacing': number;
            'text-letter-spacing': number;
            visibility: string;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | (string | number)[])[];
        layout: {
            'text-padding': number;
            'text-font': string[];
            'text-anchor': string;
            'icon-image': string;
            'text-field': string;
            'text-offset': number[];
            'text-size': number;
            'text-max-width': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-halo-blur': number;
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | (string | (string | number)[])[])[];
        layout: {
            'text-padding': number;
            'text-font': string[];
            'text-anchor': string;
            'icon-image': string;
            'text-field': string;
            'text-offset': number[];
            'text-size': number;
            'text-max-width': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-halo-blur': number;
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'text-size': {
                base: number;
                stops: number[][];
            };
            'text-font': string[];
            'text-field': string;
            'symbol-placement': string;
            'text-rotation-alignment': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-max-width'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-halo-color': string;
            'text-color': string;
            'text-halo-width': number;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | string[])[];
        layout: {
            'text-size': {
                base: number;
                stops: number[][];
            };
            'text-font': string[];
            'text-field': string;
            'symbol-placement': string;
            'text-rotation-alignment': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-max-width'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-halo-blur': number;
            'text-color': string;
            'text-halo-width': number;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-color'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | (string | number)[])[];
        layout: {
            'text-size': number;
            'icon-image': string;
            'icon-rotation-alignment': string;
            'symbol-spacing': number;
            'text-font': string[];
            'symbol-placement': {
                base: number;
                stops: (string | number)[][];
            };
            'text-rotation-alignment': string;
            'icon-size': number;
            'text-field': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-max-width'?: undefined;
            'text-letter-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'text-offset'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-color'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        source: string;
        'source-layer': string;
        minzoom: number;
        filter: (string | (string | number)[])[];
        layout: {
            'text-size': number;
            'icon-image': string;
            'icon-rotation-alignment': string;
            'symbol-spacing': number;
            'text-font': string[];
            'symbol-placement': {
                base: number;
                stops: (string | number)[][];
            };
            'text-rotation-alignment': string;
            'icon-size': number;
            'text-field': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-max-width'?: undefined;
            'text-letter-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'text-offset'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-width'?: undefined;
            'text-halo-color'?: undefined;
            'text-halo-blur'?: undefined;
        };
        metadata?: undefined;
        maxzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | string[])[];
        layout: {
            'text-letter-spacing': number;
            'text-size': {
                base: number;
                stops: number[][];
            };
            'text-font': string[];
            'text-field': string;
            'text-transform': string;
            'text-max-width': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
        };
        paint: {
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | number)[])[];
        layout: {
            'text-font': string[];
            'text-size': {
                base: number;
                stops: number[][];
            };
            'text-field': string;
            'text-max-width': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | number)[])[];
        layout: {
            'text-font': string[];
            'text-size': {
                base: number;
                stops: number[][];
            };
            'text-field': string;
            'text-max-width': number;
            'icon-image': string;
            'text-offset': number[];
            'icon-size': number;
            'text-anchor': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'text-transform'?: undefined;
        };
        paint: {
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
            'text-halo-blur'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        filter: (string | (string | number)[])[];
        layout: {
            'text-font': string[];
            'text-field': string;
            'text-size': {
                stops: number[][];
                base?: undefined;
            };
            'text-transform': string;
            'text-max-width': number;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
        };
        paint: {
            'text-halo-blur': number;
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
        };
        maxzoom?: undefined;
        minzoom?: undefined;
    } | {
        id: string;
        type: string;
        metadata: {
            'mapbox:group': string;
        };
        source: string;
        'source-layer': string;
        maxzoom: number;
        filter: (string | string[])[];
        layout: {
            'text-font': string[];
            'text-field': string;
            'text-size': number;
            'text-max-width': number;
            'text-transform': string;
            visibility?: undefined;
            'line-cap'?: undefined;
            'line-join'?: undefined;
            'text-rotation-alignment'?: undefined;
            'symbol-placement'?: undefined;
            'text-letter-spacing'?: undefined;
            'symbol-spacing'?: undefined;
            'text-padding'?: undefined;
            'text-anchor'?: undefined;
            'icon-image'?: undefined;
            'text-offset'?: undefined;
            'icon-rotation-alignment'?: undefined;
            'icon-size'?: undefined;
        };
        paint: {
            'text-halo-blur': number;
            'text-color': string;
            'text-halo-width': number;
            'text-halo-color': string;
            'background-color'?: undefined;
            'fill-color'?: undefined;
            'fill-opacity'?: undefined;
            'line-color'?: undefined;
            'line-dasharray'?: undefined;
            'fill-outline-color'?: undefined;
            'fill-antialias'?: undefined;
            'line-width'?: undefined;
            'fill-translate'?: undefined;
            'fill-pattern'?: undefined;
            'line-opacity'?: undefined;
        };
        minzoom?: undefined;
    })[];
};
export default _default;
//# sourceMappingURL=oceanic_next.d.ts.map