name: catalogue-meta-schema-check
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check-catalogue-meta-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install and build 🔧
        run: |
          pnpm install --frozen-lockfile
          pnpm exec nx run-many -t build-catalogue-meta
